### ISSUE TITLE
Running environment

### ISSUE THREAD

**Issue by leahlihe** [ChuanyuXue/tsnkit#12]
I want to ask where the src/main file is, main is not found in the src file.
I would also like to ask if the code described on the tsnkit website is running in win or linux and the version of python it is running in and so on.

**Comment by ChuanyuXue** [comment]
Please find the `src/main.py` in the legacy branch.

The main branch utilizes Python 3.11, while the legacy branch uses Python 3.7. Both are based on Linux.
