### ISSUE TITLE
Questions about the model

### ISSUE THREAD

**Issue by lianxiliangnianbandeyuan** [ChuanyuXue/tsnkit#29]
I'd like to ask if the model we created in python, the smt-nw, contains a flow scheduling process, how is this simulated, i.e. how to schedule the generated flow, or does the solver generate the flow scheduling solution directly?

**Comment by ChuanyuXue** [comment]
I don't quite understand your question but 
- `tsnkit.model.smt_nw` is used to calculate the flow schedule, generating `*.csv` files that describe the schedule.
- `tsnkit.simulation.tas` then uses these files to simulate the flow and traffic pattern when the schedule is implemented in a TSN network.
