### ISSUE TITLE
It doesn't seem to be a problem with the solver with my own file. 

### ISSUE THREAD

**Issue by dkmahao** [ChuanyuXue/tsnkit#4]
I encountered an issue using a file I created myself. It doesn't seem to be a problem with the solver. The attached image shows the issue I'm facing, and the attached file is the one I constructed.

![2](https://github.com/ChuanyuXue/tsnkit/assets/27717120/5468f8d9-cb73-4efa-80c6-086ed76be683)
![3](https://github.com/ChuanyuXue/tsnkit/assets/27717120/c3cde7c6-cbd1-494b-bec9-429f9c9df7a7)

[0_task.csv](https://github.com/ChuanyuXue/tsnkit/files/13699609/0_task.csv)
[0_topo.csv](https://github.com/ChuanyuXue/tsnkit/files/13699610/0_topo.csv)
[dataset_logs.csv](https://github.com/ChuanyuXue/tsnkit/files/13699611/dataset_logs.csv)

**Comment by ChuanyuXue** [comment]
Thank you for noticing this. 

Problem has been confirmed and supposed to be solved. Please reopen this if issue still exists.

```
➜  src git:(main) python3.9 -m tsnkit.models.cp_wa ../0_task.csv ../0_topo.csv 
| time          | name          | flag   | solve_time | total_time | total_mem 
| 21~23:56:17   | -             | succ   | 0          | 0.659      | 73.879    

➜  src git:(main) cat ../0_task.csv 
id,src,dst,size,period,deadline,jitter
0,9,[4],50,2000000,2000000,2000000
1,0,[4],50,2000000,2000000,2000000
2,0,[4],50,2000000,2000000,2000000
3,5,[9],50,2000000,2000000,2000000
4,5,[9],50,2000000,2000000,2000000
5,0,[9],50,2000000,2000000,2000000
```
