### ISSUE TITLE
variable name conflict

### ISSUE THREAD

**Issue by lxacc** [ChuanyuXue/tsnkit#8]
Under the legacy branch, In the COR2022.Py files, variable names of start_time and end_time from lines 257 to 260, conflict with variable names in lines 169 and 211.
![image](https://github.com/ChuanyuXue/tsnkit/assets/104727559/ba099e6f-3b0e-4b3c-aefe-7e79ab9fc7e3)

**Comment by ChuanyuXue** [comment]
Many thanks! Will check it soon

**Comment by ChuanyuXue** [comment]
Issue confirmed and resolved. Thank you!
