### ISSUE TITLE
Regarding the number of frames in each stream

### ISSUE THREAD

**Issue by lvihelm** [ChuanyuXue/tsnkit#9]
May I ask why it is not possible to set the number of frames per stream in the CSV file? I remember theoretically, streams in TSN allow for multiple frames, which is also an important difference between TSN and TTE. Thanks!
![流集格式](https://github.com/ChuanyuXue/tsnkit/assets/162992840/48027c8c-c1be-436b-b6a7-7ff25115555b)

**Comment by lvihelm** [comment]
What I am referring to is the number of frame instances within a stream's period, so how should I configure the CSV file to maintain the order of frames in the stream and avoid two streams interleaving in the queue?

**Comment by ChuanyuXue** [comment]
Practically, you can enlarge the frame size or reduce the period to get a result with expected orders.

Let's say you have 2 frames in one period. You can either make size = 100 or period = 50000. In this way you remain orders. But extra constraints are added (size = 100: two frames send consecutively, period = 50000: two frames send with constant interspace)

Alternatively, if the order doesn't matter, you could add one more flow.
